# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


colors_list = [
	["Blanco", "#FFFFFF"],
	["Azur", "#F0FFFF"],
	["Crema", "#F5FFFA"],
	["Nieve", "#FFFAFA"],
	["Marfil", "#FFFFF0"],
	["Cian Claro", "#E0FFFF"],
	["Amarillo Claro", "#FFFFE0"],
	["Lino", "#FAF0E6"],
	["Beige", "#F5F5DC"],
	["Lavanda", "#E6E6FA"],
	["Rosa Brumosa", "#FFE4E1"],
	["Blanco Antiguo", "#FAEBD7"],
	["Sopa", "#FFE4C4"],
	["Trigo", "#F5DEB3"],
	["Aguamarina", "#7FFFD4"],
	["Gris Claro", "#D3D3D3"],
	["Rosa", "#FFC0CB"],
	["Azul Claro", "#ADD8E6"],
	["Cardo", "#D8BFD8"],
	["Rosa Claro", "#FFB6C1"],
	["Verde Pálido", "#98FB98"],
	["Azul Cielo", "#87CEEB"],
	["Agua", "#00FFFF"],
	["Cian", "#00FFFF"],
	["Plata", "#C0C0C0"],
	["Ciruela", "#DDA0DD"],
	["Gris", "#BEBEBE"],
	["Verde Claro", "#90EE90"],
	["Violeta", "#EE82EE"],
	["Amarillo", "#FFFF00"],
	["Turquesa", "#40E0D0"],
	["Turquesa Medio", "#48D1CC"],
	["Salmón Claro", "#FFA07A"],
	["Aguamarina Medio", "#66CDAA"],
	["Gris Oscuro", "#A9A9A9"],
	["Marrón Arena", "#F4A460"],
	["Dorado", "#FFD700"],
	["Salmón Oscuro", "#E9967A"],
	["Turquesa Oscuro", "#00CED1"],
	["Coral Claro", "#F08080"],
	["Marrón Rosado", "#BC8F8F"],
	["Salmón", "#FA8072"],
	["Púrpura Medio", "#9370DB"],
	["Coral", "#FF7F50"],
	["Dorado Alambre", "#DAA520"],
	["Naranja", "#FFA500"],
	["Fucsia", "#FF00FF"],
	["Magenta", "#FF00FF"],
	["Gris Pizarra", "#708090"],
	["Tomate", "#FF6347"],
	["Naranja Oscuro", "#FF8C00"],
	["Verde Lima", "#32CD32"],
	["Lima", "#00FF00"],
	["Rojo Indio", "#CD5C5C"],
	["Rosa Intenso", "#FF1493"],
	["Chocolate", "#D2691E"],
	["Cian Oscuro", "#008B8B"],
	["Gris Aceituna", "#6B8E23"],
	["Violeta Oscuro", "#9400D3"],
	["Aceituna", "#808000"],
	["Siena", "#A0522D"],
	["Verde Bosque", "#228B22"],
	["Carmesí", "#DC143C"],
	["Azul", "#0000FF"],
	["Magenta Oscuro", "#8B008B"],
	["Marrón", "#A52A2A"],
	["Púrpura", "#800080"],
	["Verde", "#008000"],
	["Rojo", "#FF0000"],
	["Azul Medio", "#0000CD"],
	["Índigo", "#4B0082"],
	["Verde Oscuro", "#006400"],
	["Azul Oscuro", "#00008B"],
	["Azul Marino", "#000080"],
	["Rojo Oscuro", "#8B0000"],
	["Granate", "#800000"],
	["Negro", "#000000"]
]


colors_list.each do |nombre, hex_code|
	Color.find_or_create_by(name:nombre, hex_code:hex_code)
end


Season.find_or_create_by(name:"Primavera/Verano", note:"")
Season.find_or_create_by(name:"Otoño/Invierno", note:"")


category_list = [
	["Zapatillas","ZPTA"],
	["Botas","BOTA"],
	["Botinetas","BOTI"],
	["Botines","BOTE"],
	["Borcegos","BORC"],
	["Zapatos","ZPTO"],
	["Chatas","CHAT"],
	["Panchas","PANC"],
	["Mocasines","MOCA"],
	["Pantuflas","PANT"],
	["Sandalias","SAND"],
	["Zuecos","ZUEC"],
	["Guillerminas","GUIL"],
	["Ojotas","OJOT"],
	["Franciscanas","FRAN"],
	["Alpargatas","ALPA"],
	["Romanas","ROMA"],
	["Chinelas","CHIN"],
	["Stilettos","STIL"]

]

category_list.each do |nombre, code|
	Category.find_or_create_by(name:nombre, code:code)
end

release_country_list = [
["AD","Andorra", "AND"],
["AE","Emiratos Árabes Unidos", "ARE"],
["AF","Afganistán", "AFG"],
["AG","Antigua y Barbuda", "ATG"],
["AI","Anguila", "AIA"],
["AL","Albania", "ALB"],
["AM","Armenia", "ARM"],
["AN","Antillas Neerlandesas", "ANT"],
["AO","Angola", "AGO"],
["AQ","Antártida", "ATA"],
["AR","Argentina", "ARG"],
["AS","Samoa Americana", "ASM"],
["AT","Austria", "AUT"],
["AU","Australia", "AUS"],
["AW","Aruba", "ABW"],
["AX","Islas Áland", "ALA"],
["AZ","Azerbaiyán", "AZE"],
["BA","Bosnia y Herzegovina", "BIH"],
["BB","Barbados", "BRB"],
["BD","Bangladesh", "BGD"],
["BE","Bélgica", "BEL"],
["BF","Burkina Faso", "BFA"],
["BG","Bulgaria", "BGR"],
["BH","Bahréin", "BHR"],
["BI","Burundi", "BDI"],
["BJ","Benin", "BEN"],
["BL","San Bartolomé", "BLM"],
["BM","Bermudas", "BMU"],
["BN","Brunéi", "BRN"],
["BO","Bolivia", "BOL"],
["BR","Brasil", "BRA"],
["BS","Bahamas", "BHS"],
["BT","Bhután", "BTN"],
["BV","Isla Bouvet", "BVT"],
["BW","Botsuana", "BWA"],
["BY","Belarús", "BLR"],
["BZ","Belice", "BLZ"],
["CA","Canadá", "CAN"],
["CC","Islas Cocos", "CCK"],
["CF","República Centro-Africana", "CAF"],
["CG","Congo", "COG"],
["CH","Suiza", "CHE"],
["CI","Costa de Marfil", "CIV"],
["CK","Islas Cook", "COK"],
["CL","Chile", "CHL"],
["CM","Camerún", "CMR"],
["CN","China", "CHN"],
["CO","Colombia", "COL"],
["CR","Costa Rica", "CRI"],
["CU","Cuba", "CUB"],
["CV","Cabo Verde", "CPV"],
["CX","Islas Christmas", "CXR"],
["CY","Chipre", "CYP"],
["CZ","República Checa", "CZE"],
["DE","Alemania", "DEU"],
["DJ","Yibuti", "DJI"],
["DK","Dinamarca", "DNK"],
["DM","Domínica", "DMA"],
["DO","República Dominicana", "DOM"],
["DZ","Argel", "DZA"],
["EC","Ecuador", "ECU"],
["EE","Estonia", "EST"],
["EG","Egipto", "EGY"],
["EH","Sahara Occidental", "ESH"],
["ER","Eritrea", "ERI"],
["ES","España", "ESP"],
["ET","Etiopía", "ETH"],
["FI","Finlandia", "FIN"],
["FJ","Fiji", "FJI"],
["FK","Islas Malvinas", "KLK"],
["FM","Micronesia", "FSM"],
["FO","Islas Faroe", "FRO"],
["FR","Francia", "FRA"],
["GA","Gabón", "GAB"],
["GB","Reino Unido", "GBR"],
["GD","Granada", "GRD"],
["GE","Georgia", "GEO"],
["GF","Guayana Francesa", "GUF"],
["GG","Guernsey", "GGY"],
["GH","Ghana", "GHA"],
["GI","Gibraltar", "GIB"],
["GL","Groenlandia", "GRL"],
["GM","Gambia", "GMB"],
["GN","Guinea", "GIN"],
["GP","Guadalupe", "GLP"],
["GQ","Guinea Ecuatorial", "GNQ"],
["GR","Grecia", "GRC"],
["GS","Georgia del Sur e Islas Sandwich del Sur", "SGS"],
["GT","Guatemala", "GTM"],
["GU","Guam", "GUM"],
["GW","Guinea-Bissau", "GNB"],
["GY","Guayana", "GUY"],
["HK","Hong Kong", "HKG"],
["HM","Islas Heard y McDonald", "HMD"],
["HN","Honduras", "HND"],
["HR","Croacia", "HRV"],
["HT","Haití", "HTI"],
["HU","Hungría", "HUN"],
["ID","Indonesia", "IDN"],
["IE","Irlanda", "IRL"],
["IL","Israel", "ISR"],
["IM","Isla de Man", "IMN"],
["IN","India", "IND"],
["IO","Territorio Británico del Océano Índico", "IOT"],
["IQ","Irak", "IRQ"],
["IR","Irán", "IRN"],
["IS","Islandia", "ISL"],
["IT","Italia", "ITA"],
["JE","Jersey", "JEY"],
["JM","Jamaica", "JAM"],
["JO","Jordania", "JOR"],
["JP","Japón", "JPN"],
["KE","Kenia", "KEN"],
["KG","Kirguistán", "KGZ"],
["KH","Camboya", "KHM"],
["KI","Kiribati", "KIR"],
["KM","Comoros", "COM"],
["KN","San Cristóbal y Nieves", "KNA"],
["KP","Corea del Norte", "PRK"],
["KR","Corea del Sur", "KOR"],
["KW","Kuwait", "KWT"],
["KY","Islas Caimán", "CYM"],
["KZ","Kazajstán", "KAZ"],
["LA","Laos", "LAO"],
["LB","Líbano", "LBN"],
["LC","Santa Lucía", "LCA"],
["LI","Liechtenstein", "LIE"],
["LK","Sri Lanka", "LKA"],
["LR","Liberia", "LBR"],
["LS","Lesotho", "LSO"],
["LT","Lituania", "LTU"],
["LU","Luxemburgo", "LUX"],
["LV","Letonia", "LVA"],
["LY","Libia", "LBY"],
["MA","Marruecos", "MAR"],
["MC","Mónaco", "MCO"],
["MD","Moldova", "MDA"],
["ME","Montenegro", "MNE"],
["MG","Madagascar", "MDG"],
["MH","Islas Marshall", "MHL"],
["MK","Macedonia", "MKD"],
["ML","Mali", "MLI"],
["MM","Myanmar", "MMR"],
["MN","Mongolia", "MNG"],
["MO","Macao", "MAC"],
["MQ","Martinica", "MTQ"],
["MR","Mauritania", "MRT"],
["MS","Montserrat", "MSR"],
["MT","Malta", "MLT"],
["MU","Mauricio", "MUS"],
["MV","Maldivas", "MDV"],
["MW","Malawi", "MWI"],
["MX","México", "MEX"],
["MY","Malasia", "MYS"],
["MZ","Mozambique", "MOZ"],
["NA","Namibia", "NAM"],
["NC","Nueva Caledonia", "NCL"],
["NE","Níger", "NER"],
["NF","Islas Norkfolk", "NFK"],
["NG","Nigeria", "NGA"],
["NI","Nicaragua", "NIC"],
["NL","Países Bajos", "NLD"],
["NO","Noruega", "NOR"],
["NP","Nepal", "NPL"],
["NR","Nauru", "NRU"],
["NU","Niue", "NIU"],
["NZ","Nueva Zelanda", "NZL"],
["OM","Omán", "OMN"],
["PA","Panamá", "PAN"],
["PE","Perú", "PER"],
["PF","Polinesia Francesa", "PYF"],
["PG","Papúa Nueva Guinea", "PNG"],
["PH","Filipinas", "PHL"],
["PK","Pakistán", "PAK"],
["PL","Polonia", "POL"],
["PM","San Pedro y Miquelón", "SPM"],
["PN","Islas Pitcairn", "PCN"],
["PR","Puerto Rico", "PRI"],
["PS","Palestina", "PSE"],
["PT","Portugal", "PRT"],
["PW","Islas Palaos", "PLW"],
["PY","Paraguay", "PRY"],
["QA","Qatar", "QAT"],
["RE","Reunión", "REU"],
["RO","Rumanía", "ROU"],
["RS","Serbia y Montenegro", "SRB"],
["RU","Rusia", "RUS"],
["RW","Ruanda", "RWA"],
["SA","Arabia Saudita", "SAU"],
["SB","Islas Solomón", "SLB"],
["SC","Seychelles", "SYC"],
["SD","Sudán", "SDN"],
["SE","Suecia", "SWE"],
["SG","Singapur", "SGP"],
["SH","Santa Elena", "SHN"],
["SI","Eslovenia", "SVN"],
["SJ","Islas Svalbard y Jan Mayen", "SJM"],
["SK","Eslovaquia", "SVK"],
["SL","Sierra Leona", "SLE"],
["SM","San Marino", "SMR"],
["SN","Senegal", "SEN"],
["SO","Somalia", "SOM"],
["SR","Surinam", "SUR"],
["ST","Santo Tomé y Príncipe", "STP"],
["SV","El Salvador", "SLV"],
["SY","Siria", "SYR"],
["SZ","Suazilandia", "SWZ"],
["TC","Islas Turcas y Caicos", "TCA"],
["TD","Chad", "TCD"],
["TF","Territorios Australes Franceses", "ATF"],
["TG","Togo", "TGO"],
["TH","Tailandia", "THA"],
["TH","Tanzania", "TZA"],
["TJ","Tayikistán", "TJK"],
["TK","Tokelau", "TKL"],
["TL","Timor-Leste", "TLS"],
["TM","Turkmenistán", "TKM"],
["TN","Túnez", "TUN"],
["TO","Tonga", "TON"],
["TR","Turquía", "TUR"],
["TT","Trinidad y Tobago", "TTO"],
["TV","Tuvalu", "TUV"],
["TW","Taiwán", "TWN"],
["UA","Ucrania", "UKR"],
["UG","Uganda", "UGA"],
["US","Estados Unidos de América", "USA"],
["UY","Uruguay", "URY"],
["UZ","Uzbekistán", "UZB"],
["VA","Ciudad del Vaticano", "VAT"],
["VC","San Vicente y las Granadinas", "VCT"],
["VE","Venezuela", "VEN"],
["VG","Islas Vírgenes Británicas", "VGB"],
["VI","Islas Vírgenes de los Estados Unidos de América", "VIR"],
["VN","Vietnam", "VNM"],
["VU","Vanuatu", "VUT"],
["WF","Wallis y Futuna", "WLF"],
["WS","Samoa", "WSM"],
["YE","Yemen", "YEM"],
["YT","Mayotte", "MYT"],
["ZA","Sudáfrica", "ZAF"]

]

release_country_list.each do |code, name, x|
	ReleaseCountry.find_or_create_by(code:code, name:name)
end


#provider_list = [
	#["Zapatillas",""],
	#["Botas",""],
	#["Botinetas",""],
	#["Botines",""],
	#["Borcegos",""],
	#["Zapatos",""],
	#["Chatas",""],
	#["Panchas",""],
	#["Mocasines",""],
	#["Pantuflas",""],
	#["Sandalias",""],
	#["Zuecos",""],
	#["Guillerminas",""],
	#["Ojotas",""],
	#["Franciscanas",""],
	#["Alpargatas",""],
	#["Romanas",""],
	#["Chinelas",""],
	#["Stilettos",""]
#]
#
#provider_list.each do |nombre, description|
	#Provider.find_or_create_by(name:nombre, description:description)
#end




size_list = [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46]

size_list.each do |number|
	Size.find_or_create_by(number:number)
end