# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


colors_list = [
	["BLANCO", "#FFFFFF"],
	["AZUR", "#F0FFFF"],
	["CREMA", "#F5FFFA"],
	["NIEVE", "#FFFAFA"],
	["MARFIL", "#FFFFF0"],
	["BLANCO FANTASMA", "#F8F8FF"],
	["BLANCO FLORAL", "#FFFAF0"],
	["AZUL ALICIA", "#F0F8FF"],
	["CIAN CLARO", "#E0FFFF"],
	["MELÓN VERDE", "#F0FFF0"],
	["AMARILLO CLARO", "#FFFFE0"],
	["CONCHA", "#FFF5EE"],
	["SONROJO LAVANDA", "#FFF0F5"],
	["HUMO BLANCO", "#F5F5F5"],
	["ENCAJE ANTIGUO", "#FDF5E6"],
	["SEDA DE MAÍZ", "#FFF8DC"],
	["LINO", "#FAF0E6"],
	["AMARILLO ALAMBRE DORADO CLARO", "#FAFAD2"],
	["GASA LIMÓN", "#FFFACD"],
	["BEIGE", "#F5F5DC"],
	["LAVANDA", "#E6E6FA"],
	["BATIDO DE PAPAYA", "#FFEFD5"],
	["ROSA BRUMOSA", "#FFE4E1"],
	["BLANCO ANTIGUO", "#FAEBD7"],
	["BLANCO ALMENDRA", "#FFEBCD"],
	["SOPA", "#FFE4C4"],
	["TURQUESA PÁLIDO", "#AFEEEE"],
	["MOCASÍN", "#FFE4B5"],
	["GAINSBORO", "#DCDCDC"],
	["SOPLIDO MELOCOTÓN", "#FFDAB9"],
	["BLANCO NAVAJO", "#FFDEAD"],
	["DORADO ALAMBRE PÁLIDO", "#EEE8AA"],
	["TRIGO", "#F5DEB3"],
	["POLVO AZUL", "#B0E0E6"],
	["AGUAMARINA", "#7FFFD4"],
	["GRIS CLARO", "#D3D3D3"],
	["ROSA", "#FFC0CB"],
	["AZUL CLARO", "#ADD8E6"],
	["CARDO", "#D8BFD8"],
	["ROSA CLARO", "#FFB6C1"],
	["AZUL CIELO CLARO", "#87CEFA"],
	["VERDE PÁLIDO", "#98FB98"],
	["AZUL ACERO CLARO", "#B0C4DE"],
	["CAQUI", "#F0D58C"],
	["AZUL CIELO", "#87CEEB"],
	["AGUA", "#00FFFF"],
	["CIAN", "#00FFFF"],
	["PLATA", "#C0C0C0"],
	["CIRUELA", "#DDA0DD"],
	["GRIS", "#BEBEBE"],
	["VERDE CLARO", "#90EE90"],
	["VIOLETA", "#EE82EE"],
	["AMARILLO", "#FFFF00"],
	["TURQUESA", "#40E0D0"],
	["MADERA FORNIDA", "#DEB887"],
	["AMARILLO VERDE", "#ADFF2F"],
	["BRONCEADO", "#D2B48C"],
	["TURQUESA MEDIO", "#48D1CC"],
	["SALMÓN CLARO", "#FFA07A"],
	["AGUAMARINA MEDIO", "#66CDAA"],
	["GRIS OSCURO", "#A9A9A9"],
	["ORQUÍDEA", "#DA70D6"],
	["VERDE MAR INTENSO", "#8FBC8F"],
	["AZUL CIELO INTENSO", "#00BFFF"],
	["MARRÓN ARENA", "#F4A460"],
	["DORADO", "#FFD700"],
	["VERDE PRIMAVERA MEDIO", "#00FA9A"],
	["CAQUI OSCURO", "#BDB76B"],
	["ACIANO AZUL", "#6495ED"],
	["ROSA CALIENTE", "#FF69B4"],
	["SALMÓN OSCURO", "#E9967A"],
	["TURQUESA OSCURO", "#00CED1"],
	["VERDE PRIMAVERA", "#00FF7F"],
	["CORAL CLARO", "#F08080"],
	["MARRÓN ROSADO", "#BC8F8F"],
	["SALMÓN", "#FA8072"],
	["CHARTREUSE", "#7FFF00"],
	["PÚRPURA MEDIO", "#9370DB"],
	["VERDE CÉSPED", "#7CFC00"],
	["AZUL DODGER", "#1E90FF"],
	["VERDE AMARILLO", "#9ACD32"],
	["VIOLETA ROJO PÁLIDO", "#DB7093"],
	["AZUL PIZARRA MEDIO", "#7B68EE"],
	["ORQUÍDEA MEDIO", "#BA55D3"],
	["CORAL", "#FF7F50"],
	["AZUL CADETE", "#5F9EA0"],
	["VERDE MAR CLARO", "#20B2AA"],
	["DORADO ALAMBRE", "#DAA520"],
	["NARANJA", "#FFA500"],
	["GRIS PIZARRA CLARO", "#778899"],
	["FUCSIA", "#FF00FF"],
	["MAGENTA", "#FF00FF"],
	["VERDE MAR MEDIO", "#3CB371"],
	["PERÚ", "#CD853F"],
	["AZUL ACERO", "#4682B4"],
	["AZUL REAL", "#4169E1"],
	["GRIS PIZARRA", "#708090"],
	["TOMATE", "#FF6347"],
	["NARANJA OSCURO", "#FF8C00"],
	["AZUL PIZARRA", "#6A5ACD"],
	["VERDE LIMA", "#32CD32"],
	["LIMA", "#00FF00"],
	["ROJO INDIO", "#CD5C5C"],
	["ORQUÍDEA OSCURO", "#9932CC"],
	["AZUL VIOLETA", "#8A2BE2"],
	["ROSA INTENSO", "#FF1493"],
	["DORADO ALAMBRE OSCURO", "#B8860B"],
	["CHOCOLATE", "#D2691E"],
	["CIAN OSCURO", "#008B8B"],
	["GRIS DIFUSO", "#696969"],
	["GRIS ACEITUNA", "#6B8E23"],
	["VERDE MAR", "#2E8B57"],
	["VERDE CERCETA", "#008080"],
	["VIOLETA OSCURO", "#9400D3"],
	["VIOLETA ROJO MEDIO", "#C71585"],
	["NARANJA ROJO", "#FF4500"],
	["ACEITUNA", "#808000"],
	["SIENA", "#A0522D"],
	["AZUL PIZARRA OSCURO", "#483D8B"],
	["VERDE ACEITUNA OSCURO", "#556B2F"],
	["VERDE BOSQUE", "#228B22"],
	["CARMESÍ", "#DC143C"],
	["AZUL", "#0000FF"],
	["MAGENTA OSCURO", "#8B008B"],
	["GRIS PIZARRA OSCURO", "#2F4F4F"],
	["MARRÓN MONTURA", "#8B4513"],
	["MARRÓN", "#A52A2A"],
	["LADRILLO REFRACTARIO", "#B22222"],
	["PÚRPURA", "#800080"],
	["VERDE", "#008000"],
	["ROJO", "#FF0000"],
	["AZUL MEDIO", "#0000CD"],
	["ÍNDIGO", "#4B0082"],
	["AZUL MEDIANOCHE", "#191970"],
	["VERDE OSCURO", "#006400"],
	["AZUL OSCURO", "#00008B"],
	["AZUL MARINO", "#000080"],
	["ROJO OSCURO", "#8B0000"],
	["GRANATE", "#800000"],
	["NEGRO", "#000000"]
]


colors_list.each do |nombre, hex_code|
	Color.find_or_create_by(name:nombre, hex_code:hex_code)
end


Season.find_or_create_by(name:"Primavera/Verano", note:"")
Season.find_or_create_by(name:"Otoño/Invierno", note:"")


